//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinhThiThao.Areas.Admin.Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public Nullable<int> MaDM { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
